# Runs Scalafix and Scalafmt. Some Scalafix settings require a
# specific version of Scala to run and there is a Scalafmt bug in the
# latest 3.0.0-RC which prevents it from running on Scala 3.

name: Release Script Test

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-dry-run:
    name: Release Script dry run
    env:
      DRY_RUN: 1
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        scala: [2.13.6]
        java: [openjdk@1.17.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - run: git submodule update --init
      - run: ./release.sh
